version: 2

updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: monthly
      timezone: US/Arizona
    open-pull-requests-limit: 10
    assignees:
    - PHLAK

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      timezone: US/Arizona
    assignees:
      - PHLAK
